version: '3.4'

services:

########################################################################################################################
  redis1:
    build: redis/
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
    entrypoint: /start-redis.sh
    networks:
      redisnet:
########################################################################################################################
  sentinel1:
    build: redis/
    restart: always
    ports:
      - ${REDIS_SENTINEL_PORT}:26379
    env_file:
      - .env
    entrypoint: /start-sentinel.sh
    networks:
      redisnet:
########################################################################################################################
networks:
  redisnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
